namespace BuildSoft.VRChat.Osc.Input;

public enum OscButtonInput
{
    MoveForward,
    MoveBackward,
    MoveLeft,
    MoveRight,
    LookLeft,
    LookRight,
    LookDown,
    LookUp,
    Jump,
    Run,
    Back,
    Menu,
    ComfortLeft,
    ComfortRight,
    DropRight,
    UseRight,
    GrabRight,
    DropLeft,
    UseLeft,
    GrabLeft,
    PanicButton,
    QuickMenuToggleLeft,
    QuickMenuToggleRight,
    ToggleSitStand,
    AFKToggle,
}
